name: genshindb
description: A Genshin Impact app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+41

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  data_connection_checker: ^0.3.4
  device_info: ^2.0.0
  devicelocale: ^0.3.3
  dog: ^1.3.1
  enum_to_string: ^1.0.14
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.3
  flutter_colorpicker: ^0.3.5
  flutter_cupertino_localizations: ^1.0.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.4
  flutter_webview_plugin: ^0.3.11
  fluttertoast: ^7.1.8
  freezed_annotation: ^0.12.0
  get_it: ^6.0.0
  hawk_fab_menu: ^0.3.2
  image_gallery_saver: ^1.6.8
  json_annotation: ^3.1.0
  package_info: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  permission_handler: ^5.1.0+2
  rate_my_app: ^1.0.0+1
  screenshot: ^0.3.0
  shared_preferences: ^2.0.3
  smooth_star_rating: 1.1.1
  sprintf: ^6.0.0
  sqlite3_flutter_libs: ^0.4.0+1
  transparent_image: 1.0.0
  url_launcher: 5.7.10

dev_dependencies:
  build_runner: ^1.10.6
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  json_serializable: ^3.3.0
  lint: ^1.5.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/db/
    - assets/artifacts/
    - assets/characters/
    - assets/characters_full/
    - assets/elements/
    - assets/i18n/
    - assets/items/common/
    - assets/items/currency/
    - assets/items/elemental/
    - assets/items/ingredients/
    - assets/items/jewels/
    - assets/items/local/
    - assets/items/others/
    - assets/items/talents/
    - assets/items/weapon/
    - assets/items/weapon_primary/
    - assets/skills/
    - assets/weapons/
    - assets/weapons/bows/
    - assets/weapons/catalysts/
    - assets/weapons/polearms/
    - assets/weapons/claymores/
    - assets/weapons/swords/
    - assets/icon/icon.png

  fonts:
    - family: GenshinDb
      fonts:
        - asset: assets/fonts/GenshinDb.ttf

flutter_intl:
  enabled: true
